### ISSUE TITLE
Bundler throws get$iterator error

### ISSUE THREAD

**Issue by benzmarkus** [reactway/scss-bundle#92]
running the bundler results into error. With version v2.5.1 the bundler works.

[14:12:12] erro: There is an error in your styles:
[14:12:12] erro: NoSuchMethodError: method not found: 'get$iterator' (J.getInterceptor$ax(...).get$iterator is not a function) on line (undefined, undefined)

**To Reproduce**
create a scss file with the following content
=================== content start ===================
@import "~@angular/material/theming";
@import "palette";

// Include non-theme styles for core.
@include mat-core();

// Define a theme.
$primary: mat-palette($mat-liebherr-palette);
$accent: mat-palette($mat-grey, A200, A100, A400);
$warn: mat-palette($mat-deep-orange);
$theme: mat-light-theme($primary, $accent, $warn);

// Include all theme styles for the components.
@include angular-material-theme($theme);
=================== content end ===================

Run the bundler and the error appears

**Expected behavior**
success

**Package version:** v3.1.1
**Node version:** v13.12.0
**OS:** Windows

**Comment by pfeigl** [comment]
I just had the same problem when upgrading from 2.5.1 to the latest 3.1 version.

Turns out, that the `includePaths` option was pretty much `string|string[]` in 2.5.1 but is now only `string[]`.
This means, you have to have your `includePaths` configured as an array.

A better error message would have helped, but apart from that, I guess the ticket can be closed.

**Comment by hamzahsn** [comment]
I can confirm what @pfeigl  said about the array, I have faced this issue and it appeared that it is `includePaths` should be an array, and I think we should close this issue if it's solved.

**Comment by griest024** [comment]
@pfeigl has the correct solution, this can probably be closed
